version: '3.8'

services:
  v2ray:
    tty: true
    restart: always
    container_name: v2ray
    hostname: v2ray
    image: danxiaonuo/v2ray:latest
    volumes:
      # 配置目录与文件
      - ./config.json:/etc/v2ray/config.json:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
    cap_add:
     - ALL
    sysctls:
     - net.ipv4.tcp_ecn=1
     - net.ipv4.tcp_ecn_fallback=1
     - net.ipv4.tcp_congestion_control=bbrplus
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
    expose:
    - 8080
    dns:
    - 1.1.1.1
    - 8.8.8.8
